#!/bin/bash
mkdir -p Locales/fr_FR/LC_MESSAGES
msgfmt Translations/libcsuper/fr.po -o Locales/fr_FR/LC_MESSAGES/libcsuper.mo
msgfmt Translations/csuper-cli/fr.po -o Locales/fr_FR/LC_MESSAGES/csuper-cli.mo
