#!/bin/bash
sudo mkdir -p /opt/csuper
sudo cp csuper /opt/csuper
sudo cp libcsuper.so /usr/local/lib
sudo echo "nom=\$(pwd)/\$2 && cd /opt/csuper && /opt/csuper/csuper \$1 \"\$nom\"" > csuper_install
sudo chmod +x csuper_install
sudo mv csuper_install /usr/local/bin/csuper
sudo cp -R Locales /opt/csuper
