#!/bin/bash
sudo mkdir -p /usr/share/csuper
sudo cp csuper-cli /usr/share/csuper
sudo cp libcsuper.so /usr/lib
sudo cp -R Fonts /usr/share/csuper
sudo cp -R Locales /usr/share/csuper
sudo cp Installation/csuper-cli /usr/local/bin/csuper-cli
sudo chmod -R a+rx /usr/share/csuper
sudo ldconfig 
