#!/bin/bash
xgettext --sort-by-file --add-comments=TRANSLATORS: --keyword=_ -o Translations/libcsuper/messages.pot Sources/libcsuper/*.cpp
xgettext --sort-by-file --add-comments=TRANSLATORS: --keyword=_ -o Translations/csuper-cli/messages.pot Sources/csuper-cli/*.cpp

for i in Translations/libcsuper/*.po
do
	msgmerge -U $i Translations/libcsuper/messages.pot
done

for i in Translations/csuper-cli/*.po
do
	msgmerge -U $i Translations/csuper-cli/messages.pot
done
